tb/patient_medications/urls.py
from django.conf.urls import url

from careplus.residents import views

urlpatterns = [

	url(r'^$', views.residents, name='residents'),
	url(r'^(?P<id>[0-9]+)/$', views.resident, name='resident'),
    url(r'^rx_active/(?P<id>[0-9]+)/$', views.rx_active, name='rx_active'),
    url(r'^rx_overdue/(?P<id>[0-9]+)/$', views.rx_overdue, name='rx_overdue'),
    url(r'^rx_prn/(?P<id>[0-9]+)/$', views.rx_prn, name='rx_prn'),
    url(r'^rx_all/(?P<id>[0-9]+)/$', views.rx_all, name='rx_all'),
    url(r'^list/(?P<id>[0-9]+)/$', views.medicationList, name='medicationList'),
    url(r'^create/$', views.create, name='create'),
    url(r'^check/$', views.check_medications, name='check_medications'),
    url(r'^edit/(?P<id>[0-9]+)/$', views.edit, name='edit'),
    url(r'^emergency/$', views.emergencycontact, name='emergencycontact'),
    url(r'^delete/(?P<id>[0-9]+)/$', views.deleteResident, name='delete_resident'),
    

]

tb/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from importlib import reload

from tb.activities import views as activities_views
from tb.authentication import views as tb_auth_views
from tb.core import views as core_views
from tb.search import views as search_views
from rest_framework.authtoken import views

urlpatterns = [
	url(r'^$', core_views.home, name='home'),
    # The below will replace the current "home" view with "app"
    # to go to the actual app. Home will go to the marketing page.
    url(r'^app/$', core_views.app, name='app'),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
	url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v1/', include('tb.api.urls')),
    url(r'^api-token-auth/', views.obtain_auth_token),
    url(r'^login', auth_views.login, {'template_name': 'core/cover.html'},
        name='login'),
    url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),
	url(r'^signup/$', tb_auth_views.signup, name='signup'),
    url(r'^import/$', core_views.importPatients, name='import'),    
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^settings/edit/$', core_views.edit_profile, name='edit_profile'),
    url(r'^settings/picture/$', core_views.picture, name='picture'),
 
    url(r'^settings/create/$', core_views.create_medication, name='create_medication'),
    url(r'^settings/upload_picture/$', core_views.upload_picture,
        name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', core_views.save_uploaded_picture,
        name='save_uploaded_picture'),
    url(r'^settings/password/$', core_views.password, name='password'),
    url(r'^network/$', core_views.network, name='network'),
    url(r'^feeds/', include('tb.feeds.urls')),
    url(r'^medications/', include('tb.medications.urls')),
    url(r'^medications/export', core_views.medicationExport, name='export'),
    url(r'^messages/', include('tb.messenger.urls')),
    url(r'^explorer/', include('explorer.urls')),
    url(r'^notifications/$', activities_views.notifications,
        name='notifications'),
    url(r'^notifications/last/$', activities_views.last_notifications,
        name='last_notifications'),
    url(r'^notifications/check/$', activities_views.check_notifications,
        name='check_notifications'),
    url(r'^notifications/check/medications/$', activities_views.check_notifications_medication,
        name='check_notifications_medication'),
	url(r'^search/$', search_views.search, name='search'),
    url(r'^autocomplete$', search_views.autocomplete, name='autocomplete'),
    url(r'^search/get_drugs/$', search_views.GetMedicationSearch, name='autocomplete'),
    url(r'^profile/$', core_views.profile, name='profile'),
    url(r'^profile/patient/$', core_views.patients, name='patients'),
    url(r'^profile/patient/(?P<id>[0-9]+)/$', core_views.patient_medication, name='patient_medication'),
    url(r'^dashboard/$', core_views.dashboard, name='dashboard'),
    url(r'^medication/$', core_views.medication, name='medication'),
    url(r'^medication/overdue/(?P<id>[0-9]+)/$', core_views.medication_overdue, name='medication_overdue'),
    url(r'^medication/active/(?P<id>[0-9]+)/$', core_views.medication_active, name='medication_active'),
    # url(r'^clinic/$', core_views.clinicReport, name='clinic'),
    url(r'^clinic/$', core_views.clinicReport, name='clinic'),
    url(r'^registration/$', core_views.registration, name='registration'),
    url(r'^registration_tc/$', core_views.registration_page_2, name='registration_tc'),
    url(r'^registration_pharmacy/$', core_views.registration_page_3, name='registration_pharmacy'),
    url(r'^registration_notification/$', core_views.registration_page_4, name='registration_notification'),
    url(r'^users_list/$', core_views.UsersListView.as_view(), name='users_list'),
    url(r'^generate/$', core_views.GenerateRandomUserView.as_view(), name='generate'),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tb/patient_medications/models.py
from __future__ import unicode_literals
from django.dispatch import receiver
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.html import escape
from django.utils.translation import ugettext_lazy as _
from django.views.generic.edit import UpdateView
from django.template.defaultfilters import slugify
import bleach
from tb.activities.models import Activity
from django_filters import ModelMultipleChoiceFilter
from django_filters import rest_framework as filters
from django.utils import timezone
from django.db.models import signals, Count, Q
from datetime import timedelta
from django.utils import timezone
from django.db.models import signals
from itertools import chain
from operator import attrgetter
from django.core.mail import send_mail

class MedicationQuerySet(models.QuerySet):

    def medicationDeliveryTime(self):

        now = datetime.now()
        hourBefore = now - timedelta(hours=1)
        hourAfter = now + timedelta(hours=1)
        yesterday = now - timedelta(days=1)
        tomorrow = now + timedelta(days=1)


        return self.filter(medicationTimeSchedule__range=(hourBefore, hourAfter))

    def medicationDeliveryTime(self):

        now = datetime.now()
        hourBefore = now - timedelta(hours=1)
        hourAfter = now + timedelta(hours=1)

        return self.filter(medicationTimeSchedule__range=(hourBefore, hourAfter))

    def medicationDeliveryStatus(self):
        return self.filter(medicationStatus='False')

    def medicationDeliveryOverdue(self):

        now = datetime.now()
        hourAfter = now - timedelta(hours=1, minutes=1)
        currentDay = now - timedelta()

        return self.filter(medicationTimeSchedule__lte=(hourAfter))

    def medicationDeliveryOverdue2(self):

        now = datetime.now()
        hourAfter = now - timedelta(hours=1, minutes=1)
        currentDay = now - timedelta()

        return self.filter(medicationTimeSchedule2__lte=(hourAfter))

class MedicationManager(models.Manager):
    def get_queryset(self):
        return MedicationQuerySet(self.model, using=self._db)

    def medicationDeliveryTime(self):
        return self.get_queryset().medicationDeliveryTime()

    def medicationDeliveryStatus(self):
        return self.get_queryset().medicationDeliveryStatus()

    def medicationDeliveryOverdue(self):
        return self.get_queryset().medicationDeliveryOverdue()

    def medicationDeliveryOverdue2(self):
        return self.get_queryset().medicationDeliveryOverdue2()

    def medicationReset(self):
        return self.get_queryset().medicationReset()


@python_2_unicode_compatible
class Medication(models.Model):

    MISSED_CHOICES = (('False', 'False'), ('True', 'True'))
    DISCONTINUED_CHOICES = (('Active', 'Active'), ('Discontinued', 'Discontinued'))
    DISTRUBUTION_CHOICES = (('0', 'PRN - As Needed'), ('1', 'QD - 1 Times A Day'), ('2', 'BID - 2 Times A Day'), ('3', 'TID - 3 Timse A Day'), ('4', 'QID - 4 times a day'), ('5', 'SID - 5 times a day'), ('6', '6 times a day'))

    medicationName = models.CharField(verbose_name="Medication Name", default="Medication", max_length=50, null=True, blank=True)
    medicationSlug = models.SlugField(verbose_name="Slug", max_length=255, null=True, blank=True)
    medicationDosage = models.CharField(verbose_name="Dosage", default="e.g. 120 mg", max_length=50, null=True, blank=True)
    medicationFrequency = models.CharField(verbose_name="Frequency", choices=DISTRUBUTION_CHOICES, max_length=50, null=True, blank=True)
    medicationQuantity = models.IntegerField(verbose_name="Quantity", default="30", null=True, blank=True)
    medicationType = models.CharField(verbose_name="Drug Type", default="Need Options", max_length=20, null=True, blank=True)
    medicationComment = models.CharField(verbose_name="Physician Orders", max_length=500, null=True, blank=True)
    medicationStartDate = models.DateField(verbose_name="Medication Start Date", default=datetime.now, blank=True, null=True)
    medicationTimeSchedule = models.TimeField(verbose_name="Time 1",  blank=True, null=True)
    medicationTimeSchedule2 = models.TimeField(verbose_name="Time 2", blank=True, null=True)
    medicationTimeSchedule3 = models.TimeField(verbose_name="Time 3", blank=True, null=True)
    medicationTimeSchedule4 = models.TimeField(verbose_name="Time 4", blank=True, null=True)
    medicationTimeSchedule5 = models.TimeField(verbose_name="Time 5", blank=True, null=True)
    medicationTimeSchedule6 = models.TimeField(verbose_name="Time 6", blank=True, null=True)
    medicationDiscontinuedStatus = models.CharField(verbose_name="DC Status", choices=DISCONTINUED_CHOICES, max_length=15, default='Active', blank=True, null=True)
    medicationDateTimeAdded = models.DateTimeField(auto_now_add=True)
    medicationMissed = models.CharField(verbose_name="Medication Missed", choices=MISSED_CHOICES, max_length=12, default='False', blank=True, null=True)
    medicationRecordReset = models.DateTimeField(default=datetime.now, blank=True, null=True)
    user = models.ForeignKey(User)

    
    objects = MedicationQuerySet.as_manager()

    class Meta:
        verbose_name = _("Medication")
        verbose_name_plural = _("Medications")
        ordering = ('-medicationName',)


  
    def __str__(self):
        return (self.medicationName)

    # def completion_medication_set():
    #     a = Medication.objects.filter(medicationResident=1)
    #     b = a.medicationtime_set.all()
    #     medication = b.completion.all()
    #     return medication
    def get_patient_medications(user):
        medications = MedicationTime.objects.filter(medicationPatient=user)

    def get_all_medications():
        medications = MedicationTime.objects.all().order_by('medication_id')
        return medications

    def get_medications():
        medications = Medication.objects.filter(medicationDiscontinuedStatus='Active')
        return medications


    ##Chain Query Examples##
    # def get_overdue_medications():
    #     now = datetime.now()
    #     hourAfter = now - timedelta(hours=1, minutes=1)
    #     a = TimeMedicationOne.objects.filter(timeStatus2='False', timeTime__lte=hourAfter)
    #     b = TimeMedicationTwo.objects.filter(timeStatus2='False', timeTime__lte=hourAfter)
    #     medication = list(chain(a,b))
    #     return medication




 
    def get_medication(self):
        return Medication.objects.filter(medication=self)




@python_2_unicode_compatible
class MedicationTime(models.Model):

    BOOL_CHOICES = ((True, 'Accepted'), (False, 'Refused'))
    MISSED_CHOICES = (('False', 'False'), ('True', 'True'))
    STATUS_CHOICES = (('Null', 'Null'), ('False', 'False'), ('True', 'True'))

    timeDue = models.TimeField(verbose_name="Time Due", null=True, blank=True)
    timeDelivered = models.TimeField(verbose_name="Time Delivered", null=True, blank=True)
    timeStatus = models.NullBooleanField(verbose_name="Medication", choices=BOOL_CHOICES, default=None, null=True, blank=True)
    timeGivenStatus = models.CharField(verbose_name="Given", choices=STATUS_CHOICES, default=None,max_length=12, null=True, blank=True)
    timeGivenDate = models.DateTimeField(verbose_name="Date Added", auto_now_add=True)
    timeGivenNote = models.CharField(verbose_name="Notes", max_length=500, null=True, blank=True)
    timePRN = models.NullBooleanField(verbose_name="PRN?", default=None, null=True, blank=True)
    timeCreated = models.DateTimeField(verbose_name="Created")
    timeMedication = models.ForeignKey(Medication, on_delete=models.CASCADE)
 
    def __str__(self):
        return (self.timeGivenStatus)

    def get_status(self):
        return MedicationCompletion.objects.filter(completionMedication=self)

    def get_all_times():
        medication = MedicationTime.completion.all()
        return medication

    def get_overdue_medications():
        now = datetime.now()
        nextDay = now + timedelta(days=1)
        hourAfter = now - timedelta(hours=1, minutes=1)
        medication = MedicationTime.objects.filter(timeGivenStatus='False', timeDue__lte=hourAfter)
        return medication

    def get_active_medications():
        now = datetime.now()
        hourBefore = now - timedelta(hours=1)
        hourAfter = now + timedelta(hours=1)
        medication = MedicationTime.objects.filter(timeGivenStatus='False', timeDue__range=(hourBefore, hourAfter))
        return medication

    def get_prn_medications():
        medication = MedicationTime.objects.filter(timePRN=True)
        return medication



@python_2_unicode_compatible
class MedicationCompletion(models.Model):

    BOOL_CHOICES = ((True, 'Accepted'), (False, 'Refused'))
    MISSED_CHOICES = (('False', 'False'), ('True', 'True'))
    STATUS_CHOICES = (('Null', 'Null'), ('False', 'False'), ('True', 'True'))
    TIME_CHOICES = (('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'))

    completionStatus = models.NullBooleanField(verbose_name="Current Status", choices=BOOL_CHOICES, default=None, null=True, blank=True)
    completionStatus2 = models.CharField(verbose_name="Current Status 2", choices=STATUS_CHOICES, max_length=12, null=True, blank=True)
    completionMissed = models.CharField(verbose_name="Medicaton Missed", choices=MISSED_CHOICES, default='False', max_length=12, null=True, blank=True)
    completionTime = models.TimeField(verbose_name="Time Given", auto_now_add=True)
    completionDue = models.TimeField(verbose_name="Time Due", null=True, blank=True)
    completionDate = models.DateField(verbose_name="Date Given")
    completionNote = models.CharField(verbose_name="Note", max_length=500, null=True, blank=True)    
    completionMedication = models.ForeignKey(MedicationTime, related_name="completion", on_delete=models.CASCADE)
    completionRx = models.ForeignKey(Medication, on_delete=models.CASCADE)

    def __str__(self):
        return (self.completionStatus)

tb/patient_medications/forms.py
from django import forms

from careplus.residents.models import Resident, EmergencyContact
from django.utils.translation import ugettext_lazy as _


class ResidentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ResidentForm, self).__init__(*args, **kwargs)
        self.fields['residentFirstName'].required = True
        self.fields['residentLastName'].required = True
        self.fields['residentProfile'].required = False
        self.fields['residentSSN'].required = True
        self.fields['residentDOB'].required = True
        self.fields['residentPrimaryPhysician'].required = True
        self.fields['location'].required = True
        self.fields['medicareNumber'].required = True
        self.fields['dnr_status'].required = True
        self.fields['residentStatus'].required = True
    

    class Meta:
        model = Resident
        fields = ['residentFirstName', 'residentLastName', 'residentProfile', 'residentSSN', 'residentDOB', 'residentPrimaryPhysician', 'location', 'medicareNumber', 'dnr_status', 'residentStatus']


class EmergencyContactForm(forms.ModelForm):
    emergencyContactFirstName = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50)
    emergencyContactLastName = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50)
    emergencyContactRelationship = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=9)
    emergencyContactPhoneNumber = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=10)
    resident = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50)
    

    class Meta:
        model = EmergencyContact
        fields = ['emergencyContactFirstName', 'emergencyContactLastName', 'emergencyContactRelationship', 'emergencyContactPhoneNumber', 'resident']

tb/patient_medications/templates/residents/create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block head %}
  <script src="{% static 'js/residents.js' %}"></script>
{% endblock head %}

{% block main %}
  <ol class="breadcrumb">
    <li><a href="{% url 'residents' %}">{% trans 'Residents' %}</a></li>
    <li class="active">{% trans 'Create Resident' %}</li>
  </ol>
  <form action="{% url 'create' %}" method="post" role="form">
    {% csrf_token %}
    {% bootstrap_form form %}

   
    <div class="form-group">
      <button type="button" class="btn btn-primary publish">{% trans 'Create' %}</button>
      <!-- <button type="button" class="btn btn-default draft">{% trans 'Save Draft' %}</button> -->
      <!-- <button type="button" class="btn btn-default preview" data-toggle="modal" data-target="#preview">{% trans 'Preview' %}</button> -->
      <a href="{% url 'residents' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>

  <div class="modal fade" id="preview">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Resident Preview</h4>
        </div>
        <div class="modal-body"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

{% endblock main %}

tb/patient_medications/templates/residents/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block head %}
  <script src="{% static 'js/residents.js' %}"></script>
{% endblock head %}

{% block main %}
  <ol class="breadcrumb">
    <li><a href="{% url 'residents' %}">{% trans 'Residents' %}</a></li>
    <li class="active">{% trans 'Edit Resident' %}</li>
  </ol>
  <form action="{% url 'edit' form.instance.pk %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="form-group">
      <button type="button" class="btn btn-primary publish">{% trans 'Save' %}</button>
      <a href="{% url 'residents' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>


{% endblock main %}

tb/patient_medications/templates/residents/emergency.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <script src="{% static 'js/residents.js' %}"></script>
{% endblock head %}

{% block main %}
  <ol class="breadcrumb">
    <li><a href="{% url 'resident' %}">{% trans 'Resident' %}</a></li>
    <li class="active">{% trans 'Create Resident' %}</li>
  </ol>
  <form action="{% url 'create' form.instance.pk %}" method="post" role="form">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.label }}" class="control-label">{{ field.label }}</label>
      </div>
    {% endfor %}
    <div class="form-group">
      <button type="button" class="btn btn-primary publish">{% trans 'Create' %}</button>
      <!-- <button type="button" class="btn btn-default draft">{% trans 'Save Draft' %}</button> -->
      <!-- <button type="button" class="btn btn-default preview" data-toggle="modal" data-target="#preview">{% trans 'Preview' %}</button> -->
      <a href="{% url 'residents' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>


{% endblock main %}

tb/patient_medications/templates/residents/emergencyContact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <script src="{% static 'js/residents.js' %}"></script>
{% endblock head %}

{% block main %}
  <ol class="breadcrumb">
    <li><a href="{% url 'resident' %}">{% trans 'Resident' %}</a></li>
    <li class="active">{% trans 'Create Resident' %}</li>
  </ol>
  <form action="{% url 'create' form.instance.pk %}" method="post" role="form">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.label }}" class="control-label">{{ field.label }}</label>
      </div>
    {% endfor %}
    <div class="form-group">
      <button type="button" class="btn btn-primary publish">{% trans 'Create' %}</button>
      <!-- <button type="button" class="btn btn-default draft">{% trans 'Save Draft' %}</button> -->
      <!-- <button type="button" class="btn btn-default preview" data-toggle="modal" data-target="#preview">{% trans 'Preview' %}</button> -->
      <a href="{% url 'residents' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>


{% endblock main %}

tb/patient_medications/templates/residents/med_list.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
<script type="text/javascript">
function printpage() {
    //Get the print button and put it into a variable
    var printButton = document.getElementById("printIt");
    //Set the print button visibility to 'hidden' 
    printButton.style.visibility = 'hidden';
    //Print the page content
    window.print()
    //Set the print button to 'visible' again 
    //[Delete this line if you want it to stay hidden after printing]
    printButton.style.visibility = 'visible';
}
</script>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}CarePLUS{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link href="https://bootswatch.com/cerulean/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/careplus.css' %}?v=1" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="{% static 'js/careplus.js' %}"></script>
</head>

<body>
    <div class="container">
        <h1 class="text-left">{{resident.residentFirstName}} {{resident.residentLastName}}</h1>
        <h4 class="text-left">Room Number: {{resident.residentLocation}}</h4>
        <form>
            <input id="printIt" type="button" class="btn btn-danger" value="Print" onClick="printpage()">
        </form>
    </div>
    <div class="container">
        <div class="container">
            <h2 class="text-center">Medication List</h2>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Medication</th>
                        <th>Dosage</th>
                        <th>Frequency</th>
                        <th>Type</th>
                        <th>Start</th>
                        <th>Status</th>
                        <th>Count</th>
                    </tr>
                </thead>
                <tbody>
                    {% for m in med %}
                    <tr>
                        <td><a href="/medications/{{m.pk}}/">{{ m.medicationName }}</a></td>
                        <td>{{ m.medicationDosage }}</td>
                        <td>{{ m.medicationFrequency }}</td>
                        <td>{{ m.medicationType }}</td>
                        <td>{{ m.medicationStartDate }}</td>
                        <td>{{ m.medicationDiscontinuedStatus }}</td>
                        <td>{{ m.medicationQuantity }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- End Here -->
    </div>
</body>

</html>

tb/patient_medications/templates/residents/originalResident.html
 {% extends 'base.html' %} {% load staticfiles %} {% load i18n %} {% block title %} {{ resident.residentFirstName }} {{ resident.residentLastName }} {% endblock %} {% block head %}
<link href="{% static 'css/residents.css' %}" rel="stylesheet">
<script src="{% static 'js/residents.js' %}"></script>
{% endblock head %} {% block main %}
<div class="container">
    <div class="page-header">
        <h1>{{ resident.residentFirstName }} {{ resident.residentLastName }} <small>({{ resident.dnr_status }})</small></h1>
        <a href="{% url 'createMedication' resident_id=resident.id %}" class="btn btn-primary pull-right">
            <span class="glyphicon glyphicon-plus"></span> {% trans 'Add Medication' %}
        </a>
    </div>
    <div class="profile">
<!--         <div class="row">
            <div class="col-md-3 user-profile">
                <img src="http://trybootcamp.vitorfs.com/static/img/user.png" class="user-profile picture">
            </div>
        </div> -->
        <div class="col-md-3">
            <div class="list-group">
            <a href="/residents/profile/" class="list-group-item">Profile</a>
            <a href="/residents/emergency/" class="list-group-item">Contacts</a>
            <a href="/residents/emar/" class="list-group-item">Medication</a>
            </div>
        </div>
        <!-- Start Here -->
        <div class="container">
            <!-- <h2 class="text-center"><strong>Medications</strong></h2> -->
        </div>
        <div class="container">
            <div class="container">
                <h2>Medications</h2>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Medication</th>
                            <th>Frequency</th>
                            <th>Time 1</th>
                            <th>Time 2</th>
                            <th>Time 3</th>
                            <th>Time 4</th>
                            <th>Time 5</th>
                            <th>Time 6</th>
                            <th>Type</th>
                            <th>Start</th>
                            <th>Status</th>
                            <th>Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for m in resident.medication_set.all %}
                        <tr>
                            <td><a href="/medications/{{m.id}}/">{{ m.medicationName }}</a></td>
                            <td>{{ m.medicationFrequency }}</td>
                            <td><small>{{ m.medicationTimeSchedule }}</small></td>
                            <td><small>{{ m.medicationTimeSchedule2 }}</small></td>
                            <td><small>{{ m.medicationTimeSchedule3 }}</small></td>
                            <td><small>{{ m.medicationTimeSchedule4 }}</small></td>
                            <td><small>{{ m.medicationTimeSchedule5 }}</small></td>
                            <td><small>{{ m.medicationTimeSchedule6 }}</small></td>
                            <td>{{ m.medicationType }}</td>
                            <td>{{ m.medicationStartDate }}</td>
                            <td>{{ m.medicationDiscontinuedStatus }}</td>
                            <td>{{ m.medicationQuantity }}</td>
                        </tr>
                        {% endfor %}
                        <tbody>
            </div>
            <!-- End Here -->
        </div>
    </div>
    {% endblock main %}